### ISSUE TITLE
Attempt to build with SDK 2.1 fails with error in FlomioPlugin.m line 167

### ISSUE THREAD

**Issue by waimate01** [flomio/flomio_cordova_plugin#24]
Error building with the 2.1 SDK

For background, see [forum](http://flomio.com/forums/topic/phonegap-plugin-fails-to-build/) thread

/FlomioPlugin.m:167:25: error: no visible @interface for ‘FmDevice’ declares the selector ‘getDataBlocks’

**Comment by ritey** [comment]
@stuart-xyz Any idea when this may get resolved?

**Comment by damiansastre** [comment]
Does anyone have an update on this?

**Comment by grundyoso** [comment]
we have revamped our SDK interface so need to overhaul this plugin to match with it. you can fork the repo and submit PRs if you'd like to help. we're currently understaffed to take this on right now.

**Comment by damiansastre** [comment]
sadly im not an ios developer, would have to find time to learn and fork it.
I bought this device in order to build a cordova based app, bummer.

**Comment by grundyoso** [comment]
I understand. we strongly believe that web developers represent a very large market segment that we want to tap into but have just been held back with getting our native software in place first. In other words, we're committed to getting this Cordova plugin working for you with the latest Flomio SDK. It just make take a month or so. what's your application? do you need just UUID reading or full data block access??

**Comment by damiansastre** [comment]
For now I just need UUID access and it would be cool to be able to read credit card swipes from the MSR.

**Comment by grundyoso** [comment]
ok, we can offer UUID access as that's the most basic function we aim to provide. MSR card information has not been implemented even at the native iOS/Android level so that's a much more complex ask. Ping me on this thread in a couple weeks and we should have something for you to try.

**Comment by damiansastre** [comment]
Hey do you have any updates on this?

thank you!

**Comment by grundyoso** [comment]
@scottire has made progress on this and will push a formal update for you to try today/tomorrow.

**Comment by scottire** [comment]
@tagercito 
Hi,
Unfortunately because of a threading issue with the MSR, which tends to cause issues because of the use of the audio-jack port, there has been a delay with the release of the cordova bridge support for the MSR. I will continue working on it and update you early next week (or earlier if it's good news).

**Comment by scottire** [comment]
It is worth putting here that NDEF reading is now supported when using a FloBLE Plus device on branch v2.2. There are still issues with threading using the Flojack MSR.

**Comment by damiansastre** [comment]
I will be compiling version 2.2 with this cordova plugin today. will keep you posted.
