### ISSUE TITLE
Error building using PhoneGap Build

### ISSUE THREAD

**Issue by tylervz** [flomio/flomio_cordova_plugin#27]
I added the plugin to our project using

    cordova plugin add https://github.com/flomio/flomio_cordova_plugin#2b76e4ec347b0f285e2a58c8b0c6b01522f93bf4

then committed and pushed the changes to `config.xml` and `package.json`.

When I attempted to make a new iOS build on PhoneGap Build, I got an error:

![image](https://user-images.githubusercontent.com/8753239/29331334-ad49e86c-81c1-11e7-837b-5bcdea71a560.png)

I have Cordova version 7.0.1 installed, and PhoneGap Build is making builds using version 6.5.0.

Then I tried to build the iOS app locally, but I got an error when I ran `cordova build ios`: 

```
ld: warning: ignoring file /Users/tylervanzanten/src/hypercision/rollcall/mobile/rollCallUI5/platforms/ios/RollCall/Plugins/com.flomio.sdk/libSDKClasses.a, missing required architecture x86_64 in file /Users/tylervanzanten/src/hypercision/rollcall/mobile/rollCallUI5/platforms/ios/RollCall/Plugins/com.flomio.sdk/libSDKClasses.a (2 slices)
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_FmSessionManager", referenced from:
      objc-class-ref in FlomioPlugin.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by scottire** [comment]
You need to build using a connected device. try `cordova build ios --device` after connecting your phone.

**Comment by tylervz** [comment]
I was able to build and launch the app successfully from Xcode. Any idea on why the build fails on Phonegap Build though?

**Comment by scottire** [comment]
It's due to the architecture files which are needed in the drivers in the Flomio SDK. You can get it to play nicely by `cordova build ios --release`. Are you not able to use Phonegap to launch the app?

**Comment by tylervz** [comment]
No, not at the moment. When I run `cordova run ios --device` I get this error: https://github.com/phonegap/ios-deploy/issues/292

**Comment by scottire** [comment]
Hmm... I have not seen that error. This seems to be an error with your setup. Have you tried following the advice in the thread, making sure your `ios-deploy` `xcode-select` `cordova` versions are all up to date.

Here is my setup: 
cli packages: (node_modules)

    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

global packages:

    Cordova CLI : 6.5.0 

local packages:

    @ionic/app-scripts : 2.1.3
    Cordova Platforms  : ios 4.3.1
    Ionic Framework    : ionic-angular 3.6.0

System:

    ios-deploy        : 1.9.1 
    ios-sim           : 5.0.13 
    Node              : v6.11.0
    npm               : 3.10.10 
    OS                : macOS Sierra
    Xcode             : Xcode 9.0 Build version 9M202q 

xcode-select -v
xcode-select version 2347.
Scott

**Comment by tylervz** [comment]
I got `cordova run ios --device` working by following [this advice](https://github.com/phonegap/ios-deploy/issues/292#issuecomment-307491341). My device was running iOS 10.3.2 but there was only DeviceSupport for 10.3.1.

Should this issue be closed since it seems that support for PhoneGap Build is not possible?

**Comment by scottire** [comment]
I just tried `cordova build ios --release` and have been able to get it to build successfully locally. Can you not?

**Comment by tylervz** [comment]
I can build locally just fine. I can't build using [Adobe Phonegap Build](https://build.phonegap.com):

![image](https://user-images.githubusercontent.com/8753239/29331334-ad49e86c-81c1-11e7-837b-5bcdea71a560.png)

**Comment by scottire** [comment]
Ok, I will close this then. We do not support Adobe PhoneGap Build cloud service at the moment.
